# Generated by Django 3.1.6 on 2021-02-14 10:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210214_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Phim hành động', 'Phim hành động'), ('Phim hài hước', 'Phim hài hước'), ('Phim võ thuật', 'Phim võ thuật'), ('Phim kinh dị', 'Phim kinh dị'), ('Phim tâm lý', 'Phim tâm lý'), ('Phim gia đình', 'Phim gia đình'), ('Phim hoạt hình', 'Phim hoạt hình')], max_length=256, null=True),
        ),
    ]
