# Generated by Django 3.1.6 on 2021-02-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210214_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='question',
            new_name='product',
        ),
    ]
