# Generated by Django 3.1.6 on 2021-02-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210214_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='type_text',
        ),
    ]
