# Generated by Django 3.1.6 on 2021-02-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210214_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type_text',
            field=models.CharField(blank=True, choices=[('Phim hành động', 'Phim hành động'), ('Phim hài hước', 'Phim hài hước'), ('Phim viễn tưởng', 'Phim viễn tưởng'), ('Phim kinh dị', 'Phim kinh dị'), ('Phim tâm lý', 'Phim tâm lý'), ('Phim gia đình', 'Phim gia đình'), ('Phim hoạt hình', 'Phim hoạt hình')], max_length=256, null=True),
        ),
    ]
